# Generated by Django 3.1.2 on 2020-10-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_link',
            field=models.URLField(null=True),
        ),
    ]
