# Generated by Django 3.1.2 on 2020-10-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fblog', '0002_post_short_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='count_viewer',
            field=models.IntegerField(default=0),
        ),
    ]
