# Generated by Django 3.1.2 on 2020-10-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fblog', '0003_post_count_viewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='short_link',
            field=models.URLField(default='https://www.google.com/'),
        ),
    ]
